version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - ./src/prod.env
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3000:3000
    networks:
      - common-network
  mysql-container:
    image: mysql
    ports:
      - '3307:3306'
    volumes:
      - /User/lighthouse/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_sys
      MYSQL_ROOT_PASSWORD: dchih
    networks:
      - common-network
  redis-container:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - /User/lighthouse/redis:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
