version: '3.8'
services:
  nest-app:
    build:
      context: ./
    env_file:
      - ./src/.env
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3005:3005
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - D:\\mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_sys
      MYSQL_ROOT_PASSWORD: dchih
    networks:
      - common-network
  redis-container:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - D:\\dockerdata\redis:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
